# Generated by Django 5.2 on 2025-09-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BricsComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('mean_gdp_zar_bn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('median_inflation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gdp_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gdp_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inflation_mode', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('insights', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('gdp_zar_bn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inflation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gdp_yoy_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inflation_yoy_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('era', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='StatisticalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(db_index=True, max_length=50)),
                ('mean_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('median_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('std_dev', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolatilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdp_yoy_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inflation_yoy_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volatility_flag', models.BooleanField(db_index=True, default=False)),
                ('is_outlier', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.OneToOneField(db_column='year', on_delete=django.db.models.deletion.CASCADE, related_name='volatility', to='analysis.economicindicator', to_field='year')),
            ],
        ),
    ]
